apiVersion: v2
publisher: redhat
name: quarkus-java11
version: 1.3.0a
type: VS Code extension
displayName: Quarkus, Maven, Gradle and Java 11 Language Support
title: Quarkus, Java 11, Maven, and Gradle Tools by Red Hat
description: Support for Quarkus, Maven, Gradle. Java Linting, Intellisense, formatting, refactoring, debugging, and language server.
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/dependencies/che-plugin-registry/resources/images/default.svg?sanitize=true
repository: https://github.com/redhat-developer/vscode-quarkus
category: Language
firstPublicationDate: "2020-02-12"
spec:
  containers:
    - image: "registry.redhat.io/codeready-workspaces/plugin-java11-rhel8:2.2"
      name: vscode-quarkus
      memoryLimit: "3500Mi"
      args:
        - sh
        - -c
        - ${PLUGIN_REMOTE_ENDPOINT_EXECUTABLE}
      volumes:
      - mountPath: "/home/jboss/.m2"
        name: m2
      - mountPath: "/home/jboss/.gradle"
        name: gradle
  extensions:
    - https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-java-debug/vscode-java-debug-0.24.0.vsix
    - https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.57.0-2029.vsix
    - https://download.jboss.org/jbosstools/vscode/stable/vscode-quarkus/vscode-quarkus-1.3.0-242.vsix
